--- 
- name: Perform some basic tasks on remote hosts.
  hosts: localhost #define which groups to run the tasks on. 
  become: no #tell if the task has to be done in a privileged mode. 
  
  tasks: # list the tasks to be executed. 
    - name: Create a file directory
      ansible.builtin.file:
        path: /tmp/my_ansible_created_dir
        state: directory
        mode: '0755'
    
    - name: Check if directory exists
      ansible.builtin.stat:
        path: /tmp/my_ansible_created_dir
      register: dir_stat

    - name: Print the directory status
      ansible.builtin.debug:
        msg: "Directory exists: {{dir_stat.stat.exists }}"

    - name: Create an empty file
      ansible.builtin.file:
        path: /tmp/my_ansible_created_dir/my_ansible_created_file.txt
        state: touch

    - name: Check if the empty file exists
      ansible.builtin.stat:
        path: /tmp/my_ansible_created_dir/my_ansible_created_file.txt
      register: file_stat

    - name: Print the empty file status
      ansible.builtin.debug:
        msg: "Empty file exists: {{file_stat.stat.exists}}"